// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250818090001_Update Seed")]
    partial class UpdateSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67baf9d3-1f6a-4273-bbdb-0a97e42582cb"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("8d0618e1-5d64-4aa4-bb42-254767ec3752"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("812d6ace-115c-4866-83bc-1b162dce1d5a"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7044cdb-f20f-4a90-893a-e357f2aecdf0"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/4.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100001"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/5.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100002"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/1.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100003"),
                            Code = "HLZ",
                            Name = "Hamilton",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/2.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100004"),
                            Code = "TRG",
                            Name = "Tauranga",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/3.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100005"),
                            Code = "NPE",
                            Name = "Napier",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/4.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100006"),
                            Code = "DUD",
                            Name = "Dunedin",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/5.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100007"),
                            Code = "PMR",
                            Name = "Palmerston North",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/1.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100008"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/2.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100009"),
                            Code = "ROT",
                            Name = "Rotorua",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/3.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100010"),
                            Code = "NPL",
                            Name = "New Plymouth",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/4.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100011"),
                            Code = "IVC",
                            Name = "Invercargill",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/5.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100012"),
                            Code = "WRE",
                            Name = "Whangarei",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/1.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100013"),
                            Code = "GIS",
                            Name = "Gisborne",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/2.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100014"),
                            Code = "TIU",
                            Name = "Timaru",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/3.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100015"),
                            Code = "ZQN",
                            Name = "Queenstown",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/4.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100016"),
                            Code = "MST",
                            Name = "Masterton",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/5.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100017"),
                            Code = "KKR",
                            Name = "Kaikoura",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/1.sm.jpg"
                        },
                        new
                        {
                            Id = new Guid("a18c7c1d-8a27-42f5-9e30-5a5cce100018"),
                            Code = "TUO",
                            Name = "Taupo",
                            RegionImageUrl = "https://www.gstatic.com/webp/gallery/2.sm.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
